name: Linked Issue Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  linked-issue:
    name: Require Linked Issue
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: nearform-actions/github-action-check-linked-issues@a291ab7b9a0d34eda80f837d5e9009a6ca78d133 # v1.8.3
        id: check-linked-issues
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude-branches: "dependabot/**"
          exclude-labels: "skip-issue-check, documentation"
          comment: false
